import { Model } from 'sequelize-typescript';

export type StronglyTypedModel<T extends Model> = Omit<T,
    '$add'
    | '$get'
    | '$set'
    | '$count'
    | '$create'
    | '$has'
    | '$remove'
    | 'reload'
    | 'isNewRecord'
    | 'createdAt'
    | 'updatedAt'
    | 'isDeleted'
    | 'getDataValue'
    | 'setDataValue'
    | 'get'
    | 'set'
    | 'setAttributes'
    | 'where'
    | 'sequelize'
    | 'changed'
    | 'previous'
    | 'save'
    | 'validate'
    | 'update'
    | 'destroy'
    | 'restore'
    | 'increment'
    | 'decrement'
    | 'equals'
    | 'equalsOneOf'
    | 'toJSON'
    | 'addHook'
    | 'removeHook'
    | 'hasHook'
    | 'hasHooks'
    | 'id'> & { id?: string };
